### ISSUE TITLE
Some songs refuse to download. (403)

### ISSUE THREAD

**Issue by cory2067** [next2e/2E-Music#12]
I have no idea why this happens, but the problem seems to be getting worse.

for example, could not download this song both locally and on the server:
https://www.youtube.com/watch?v=nMwLbAZMdV4

**Comment by cory2067** [comment]
Update, it's a 403 error on presumably copyrighted songs for which youtube prohibits external streaming.
Will try to find workaround

**Comment by MFarejowicz** [comment]
Ooh, that's a really nice catch. It would be cool to find a workaround, but at least we know what the issue is.

**Comment by cory2067** [comment]
stopped happening, actually probably a trash issue with the IS&T blocking youtube stuff that we can't really control
